import React, { useState, useEffect } from "react";
import { Folder, ArrowRight, Clock, Box, PlusCircle, SortAsc, SortDesc, Calendar as CalendarIcon, Type, Activity } from "lucide-react";
import { motion } from "motion/react";
import { Link } from "react-router-dom";
import { Project, fetchProjects } from "../lib/api";
import Layout from "../components/Layout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";

type SortOption = "date_desc" | "date_asc" | "alpha_asc" | "alpha_desc";

export default function LandingPage() {
  const [projects, setProjects] = useState<Project[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [sortBy, setSortBy] = useState<SortOption>("date_desc");

  useEffect(() => {
    async function load() {
      try {
        const data = await fetchProjects();
        setProjects(data);
      } catch (err: any) {
        setError(err.message || String(err));
      } finally {
        setIsLoading(false);
      }
    }
    load();
  }, []);

  const sortedProjects = [...projects].sort((a, b) => {
    switch (sortBy) {
      case "date_desc":
        return new Date(b.created_at).getTime() - new Date(a.created_at).getTime();
      case "date_asc":
        return new Date(a.created_at).getTime() - new Date(b.created_at).getTime();
      case "alpha_asc":
        return a.name.localeCompare(b.name);
      case "alpha_desc":
        return b.name.localeCompare(a.name);
      default:
        return 0;
    }
  });

  return (
    <Layout>
      <div className="max-w-5xl mx-auto px-8 py-12">
        {error && (
          <Card className="mb-8 border-red-100 bg-red-50/50 shadow-sm overflow-hidden">
            <CardHeader className="flex flex-row items-center gap-4 pb-2">
              <div className="w-10 h-10 bg-red-100 rounded-xl flex items-center justify-center text-red-600">
                <Activity className="w-5 h-5" />
              </div>
              <div>
                <p className="font-black uppercase tracking-widest text-[10px] text-red-500">Database Connection Error</p>
                <CardTitle className="text-red-700">{error}</CardTitle>
              </div>
            </CardHeader>
            <CardContent className="pt-4">
              {(error.includes("projects") || error.includes("api_keys")) && (
                <div className="space-y-6">
                  <p className="text-[10px] font-black text-slate-500 uppercase tracking-widest">Required Database Setup</p>
                  
                  {error.includes("projects") && (
                    <div className="space-y-2">
                      <p className="text-[10px] font-bold text-red-500 uppercase">Run this in Supabase SQL Editor:</p>
                      <pre className="text-[10px] font-mono bg-white p-4 rounded-xl border border-red-100 overflow-x-auto leading-relaxed shadow-inner">
                        {`CREATE TABLE projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  query TEXT DEFAULT '',
  settings JSONB DEFAULT '{}',
  user_email TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  snippet TEXT,
  source TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE api_keys (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_email TEXT NOT NULL,
  key_value TEXT NOT NULL,
  service_name TEXT DEFAULT 'tavily',
  label TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE vault_users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  full_name TEXT NOT NULL,
  role TEXT DEFAULT 'User',
  access_start_date TIMESTAMPTZ DEFAULT now(),
  access_end_date TIMESTAMPTZ DEFAULT (now() + interval '1 year'),
  created_at TIMESTAMPTZ DEFAULT now()
);`}
                      </pre>
                    </div>
                  )}

                  {error.includes("schema cache") && (
                    <div className="space-y-2">
                      <p className="text-[10px] font-bold text-red-500 uppercase">Refresh Schema Cache:</p>
                      <p className="text-xs text-slate-600 font-medium">If you just ran the SQL, please wait a moment or check if the tables are visible in your Supabase dashboard.</p>
                    </div>
                  )}
                </div>
              )}
            </CardContent>
          </Card>
        )}
        
        <div className="flex flex-col md:flex-row md:items-end justify-between mb-12 gap-6">
          <div className="text-center md:text-left">
            <h1 className="text-3xl font-black text-slate-900 tracking-tight mb-2 uppercase">Project Laboratory</h1>
            <p className="text-slate-500 font-medium tracking-tight">Active research streams and knowledge aggregates.</p>
          </div>

          <div className="flex items-center gap-1 self-center md:self-end bg-white border border-slate-200 rounded-xl p-1 shadow-sm">
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button 
                    variant={sortBy === 'date_desc' ? 'default' : 'ghost'}
                    size="sm"
                    onClick={() => setSortBy("date_desc")}
                    className={sortBy === 'date_desc' ? 'bg-primary text-white shadow-md shadow-primary/20' : 'text-slate-400'}
                  >
                    <CalendarIcon className="w-3.5 h-3.5 mr-1" />
                    <SortDesc className="w-3 h-3" />
                  </Button>
                </TooltipTrigger>
                <TooltipContent><p>Newest First</p></TooltipContent>
              </Tooltip>
            </TooltipProvider>

            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button 
                    variant={sortBy === 'date_asc' ? 'default' : 'ghost'}
                    size="sm"
                    onClick={() => setSortBy("date_asc")}
                    className={sortBy === 'date_asc' ? 'bg-primary text-white shadow-md shadow-primary/20' : 'text-slate-400'}
                  >
                    <CalendarIcon className="w-3.5 h-3.5 mr-1" />
                    <SortAsc className="w-3 h-3" />
                  </Button>
                </TooltipTrigger>
                <TooltipContent><p>Oldest First</p></TooltipContent>
              </Tooltip>
            </TooltipProvider>

            <div className="w-px h-6 bg-slate-100 mx-1" />

            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button 
                    variant={sortBy === 'alpha_asc' ? 'default' : 'ghost'}
                    size="sm"
                    onClick={() => setSortBy("alpha_asc")}
                    className={sortBy === 'alpha_asc' ? 'bg-primary text-white shadow-md shadow-primary/20' : 'text-slate-400'}
                  >
                    <Type className="w-3.5 h-3.5 mr-1" />
                    <SortAsc className="w-3 h-3" />
                  </Button>
                </TooltipTrigger>
                <TooltipContent><p>Alphabetical (A-Z)</p></TooltipContent>
              </Tooltip>
            </TooltipProvider>

            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button 
                    variant={sortBy === 'alpha_desc' ? 'default' : 'ghost'}
                    size="sm"
                    onClick={() => setSortBy("alpha_desc")}
                    className={sortBy === 'alpha_desc' ? 'bg-primary text-white shadow-md shadow-primary/20' : 'text-slate-400'}
                  >
                    <Type className="w-3.5 h-3.5 mr-1" />
                    <SortDesc className="w-3 h-3" />
                  </Button>
                </TooltipTrigger>
                <TooltipContent><p>Alphabetical (Z-A)</p></TooltipContent>
              </Tooltip>
            </TooltipProvider>
          </div>
        </div>

        {isLoading ? (
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {[1, 2, 3, 4, 5, 6, 7, 8].map((i) => (
              <Card key={i} className="h-32 border-slate-200 animate-pulse bg-white/50" />
            ))}
          </div>
        ) : sortedProjects.length === 0 ? (
          <Card className="flex flex-col items-center justify-center py-20 bg-white rounded-3xl border-dashed border-slate-200">
            <div className="w-16 h-16 bg-slate-50 rounded-2xl flex items-center justify-center text-slate-200 mb-6 border border-slate-100 shadow-inner">
              <Box className="w-8 h-8" />
            </div>
            <CardTitle className="text-xl text-slate-900 mb-2">No Active Streams</CardTitle>
            <CardDescription className="text-center max-w-xs mb-8">
              Initiate your first research project by clicking the button in the sidebar.
            </CardDescription>
          </Card>
        ) : (
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
            {sortedProjects.map((project, idx) => (
              <motion.div
                key={project.id}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: idx * 0.05 }}
              >
                <Link to={`/project/${project.id}`}>
                  <Card className="group h-full border-slate-200 hover:border-primary/50 hover:shadow-xl transition-all relative overflow-hidden bg-white">
                    <div className="absolute top-0 right-0 w-20 h-20 bg-slate-50 rounded-full translate-x-10 -translate-y-10 group-hover:bg-primary/5 transition-colors" />
                    
                    <CardHeader className="p-4 relative z-10">
                      <div className="flex items-center gap-2 mb-2">
                        <div className="p-1.5 bg-slate-100 rounded-lg group-hover:bg-primary group-hover:text-white transition-all shadow-sm">
                          <Folder className="w-4 h-4" />
                        </div>
                        <div className="flex flex-col">
                          <Badge variant="outline" className="w-fit h-4 text-[8px] font-black uppercase tracking-widest text-slate-400 group-hover:text-primary transition-colors border-none p-0">
                            Captured {new Date(project.created_at).toLocaleDateString()}
                          </Badge>
                          <CardTitle className="text-sm font-bold text-slate-800 truncate group-hover:text-primary transition-colors">{project.name}</CardTitle>
                        </div>
                      </div>
                      <CardDescription className="line-clamp-2 leading-tight text-slate-500 text-[11px] min-h-[1.5rem]">
                        {project.query || "No parameters set."}
                      </CardDescription>
                    </CardHeader>

                    <CardFooter className="p-4 pt-0 mt-auto border-t border-slate-50 relative z-10 flex items-center justify-between">
                      <div className="flex items-center gap-2 text-[9px] font-mono font-bold text-slate-400">
                        <Clock className="w-3 h-3 text-primary/60" /> 
                        {new Date(project.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                      </div>
                      <ArrowRight className="w-4 h-4 text-slate-300 group-hover:text-primary group-hover:translate-x-1 transition-all" />
                    </CardFooter>
                  </Card>
                </Link>
              </motion.div>
            ))}
          </div>
        )}
      </div>
    </Layout>
  );
}
